# Aquí definimos la clase de implementación de encriptación por defecto.

# Opción 1: Usar AES
#defaultEncryptionClass = encriptacion.ProcesoEncriptarAES

# Opción 2: Usar Blowfish (solo descomenta esta y comenta la de AES)
#defaultEncryptionClass = encriptacion.ProcesoEncriptarBlowfish

# Opción 3: Sin encriptar
defaultEncryptionClass = encriptacion.ProcesoSinEncriptar